Update configure

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -33,7 +33,7 @@ fi
 if $(type python >/dev/null 2>&1); then
 	echo "python installed"
 else
-	echo >&2 "bedtools must be installed.  Aborting."; exit 1
+	echo >&2 "python must be installed.  Aborting."; exit 1
 fi
 
 if $(python -c "import matplotlib" &> /dev/null); then
